In [22]:
import numpy as np
array1=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
npArray=np.array(array1)
print(npArray)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
print(npArray.ndim,"dimenstional array")
print(npArray.shape,"matrix array")


2 dimenstional array
(4, 3) matrix array


In [27]:
print(npArray.reshape(6,2))



[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [32]:
array=np.arange(-10,10,2)
print(array)

[-10  -8  -6  -4  -2   0   2   4   6   8]


Array creations

In [34]:
import numpy as np

array=np.empty((3,2),dtype=np.int)
print(array)

[[-1332331552         675]
 [          0           0]
 [     131074           0]]


Indexing and Slicing

In [49]:
array=np.random.randint(1,10,(2,2))
print(array)

[[1 3]
 [7 5]]


In [50]:
array1=array/10
print(array1)

[[0.1 0.3]
 [0.7 0.5]]


In [52]:
arrayMul=np.matmul(array1,array1)
print(array1 )
print(arrayMul)

[[0.1 0.3]
 [0.7 0.5]]
[[0.22 0.18]
 [0.42 0.46]]


In [53]:
array=np.random.randint(1,10,(3,3))
print(array)

[[1 7 9]
 [7 8 6]
 [1 7 5]]


In [54]:
print(np.max(array))

9


In [55]:
print(np.argmax(array))#index of max value

2


In [57]:
print(np.max(array,axis=0)) #get max of each column

[7 8 9]


In [67]:
print(array[1,2])#specify row and columns

6


<h3>numpy and pandas</h3>

In [82]:
import pandas as pd
dataset=pd.read_csv(r'C:\Users\saileo\Downloads\student_marks.csv')

In [83]:
print(dataset)

  Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05/04/1988     55       45       56.0       87       21   
1     Suresh      M    4/5/1987     75       55        NaN       64       90   
2     Ramesh      M   25/5/1989     25       54       89.0       76       95   
3    Jessica      F   12/8/1990     78       55       86.0       63       54   
4   Jennifer      F    2/9/1989     58       96       78.0       46       96   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
