In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [4]:
np.__version__

'1.19.2'

In [5]:
dis=[1,2,3]
t=[1,3,2]


In [6]:
d=np.array(dis)

In [7]:
d

array([1, 2, 3])

In [8]:
#Scalar

a = np.array(10)

In [26]:
print(type(a))
a

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#vector
b =np.array([1,2,3,4])
type(b)
b

array([1, 2, 3, 4])

In [11]:
#matrices
M= np.array([[1,2,3,4,5,6],[7,8,9,4,5,6]])

print(M)

[[1 2 3 4 5 6]
 [7 8 9 4 5 6]]


In [12]:
m =np.matrix([[1,2,3,4,5,6],[7,8,9,4,5,6]])
print(m)

[[1 2 3 4 5 6]
 [7 8 9 4 5 6]]


In [13]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [14]:
#arrays
#if other data type is added all data is upcasted to that data type
a=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(a)


[[1 2 3 4 5]
 [3 4 5 6 7]]


In [15]:
b=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(b)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [16]:
b.shape

(2, 5)

In [17]:
b.size

10

In [18]:
b.dtype

dtype('int32')

In [19]:
b.itemsize

4

In [20]:
b.ndim

2

In [21]:
a[0][-1]

5

In [22]:
a[:,2]

array([3, 5])

In [23]:
#arange 
a=np.arange(10)

In [27]:
b=np.arange(1,10)

In [29]:
c=np.arange(30, dtype='complex')
c

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j, 20.+0.j,
       21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j, 25.+0.j, 26.+0.j, 27.+0.j,
       28.+0.j, 29.+0.j])

In [32]:
#zeros
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
iz=np.zeros((10,10),dtype='int')
iz

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [68]:
ones=np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
#linspace
o=np.linspace
o

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In [44]:
#identity matrix eye
identity=np.eye(5,5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
i2=np.eye(4)
i2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
i3=np.identity(5)
i3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
#random
rand=np.random.rand(10,2)
rand

array([[0.94675745, 0.92744214],
       [0.71847436, 0.28594822],
       [0.15438953, 0.24414961],
       [0.06178519, 0.18834622],
       [0.37196401, 0.20844593],
       [0.26344259, 0.42022328],
       [0.53985218, 0.24794426],
       [0.3377163 , 0.80001129],
       [0.29329585, 0.05529275],
       [0.71231788, 0.60650463]])

In [54]:
#reshape and resize 
rand.shape


(10, 2)

In [56]:
rand.reshape(5,4)

array([[0.94675745, 0.92744214, 0.71847436, 0.28594822],
       [0.15438953, 0.24414961, 0.06178519, 0.18834622],
       [0.37196401, 0.20844593, 0.26344259, 0.42022328],
       [0.53985218, 0.24794426, 0.3377163 , 0.80001129],
       [0.29329585, 0.05529275, 0.71231788, 0.60650463]])

In [62]:
rand.resize(4,5)

In [63]:
rand

array([[0.94675745, 0.92744214, 0.71847436, 0.28594822, 0.15438953],
       [0.24414961, 0.06178519, 0.18834622, 0.37196401, 0.20844593],
       [0.26344259, 0.42022328, 0.53985218, 0.24794426, 0.3377163 ],
       [0.80001129, 0.29329585, 0.05529275, 0.71231788, 0.60650463]])

In [80]:
print(b)
b.reshape(3,3)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
print(b)

[1 2 3 4 5 6 7 8 9]


In [83]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [84]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6])

In [90]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6])

In [92]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6])

In [93]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6])

In [95]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:

arr1.ravel('k')

array([1, 2, 3, 4, 5, 6])

In [98]:
arr_2d = np.array([ [0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8]])

In [99]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### C’: Read items from array row wise i.e. using C-like index order.
##### F’: Read items from array column wise i.e. using Fortran-like index order.
##### K’: Read items from array based on memory order of items

In [100]:
arr_2d.ravel('C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
arr_2d.ravel('F')

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [103]:
arr_2d.ravel('K')

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
arr_2d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])